/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/
#include "decision.h"


#ifndef BASIC_STRATEGY_H
#define BASIC_STRATEGY_H


namespace Basic_strategy{
  char move_split(int x, int y);
  char move_ace(int x, int y);
  char move_normal(int x, int y);
// const char d_hit = 'f';
// const char d_dou =  'd';
// const char d_sta = 's';
// const char d_spl = 'a';
// 
// 
// class Basic_strategy
// {
// };
// 
// const Decision normal[16][10]
// {
// //2		3	4	5	6	  7	    8		9	10	ace
//     (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), //5
//     (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), //6
//     (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_hit), (d_dou), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), //9
//     (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit),//10
//     (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit),
//     (d_hit), (d_hit), (d_sta), (d_sta), (d_sta), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),//12
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),//15
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),//16
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta),//17
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta),
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta),
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta),//20
// };
// 
// 
// const Decision soft_ace[8][10]
// {
//     (d_hit), (d_hit), (d_hit), (d_dou), (d_dou), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),	//2
//     (d_hit), (d_hit), (d_hit), (d_dou), (d_dou), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_hit), (d_hit), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),//4
//     (d_hit), (d_hit), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_hit), (d_dou), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_sta), (d_dou), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),//7
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta),
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta),
// };
// 
// const Decision split[10][10] {
//     (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), //a-a
//     (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_hit), (d_hit), (d_hit), (d_hit),	
//     (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_hit), (d_hit), (d_hit), (d_hit),	
//     (d_hit), (d_hit), (d_hit), (d_spl), (d_spl), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),	
//     (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit),	//5
//     (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_hit), (d_hit), (d_hit), (d_hit),//7
//     (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_spl),
//     (d_spl), (d_spl), (d_spl), (d_spl), (d_spl), (d_sta), (d_spl), (d_spl), (d_sta), (d_sta),
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta)
// };
// 
  
}
// char move(const Decision table[][10],int x, int y){
//   return table[x][y].get(0);
// }

//				dopracować ????
// const Decision
// const char d_hit = 'f';
// const char d_dou =  'd';
// const char d_sta = 's';
// const char d_spl = 'a';
//
// class Basic_strategy
// {
// };
//
// const Decision normal[16][10]
// {
// //2		3	4	5	6	  7	    8		9	10	ace
//     (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), //5
//     (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), //6
//     (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_hit), (d_dou), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit), //9
//     (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit),//10
//     (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_dou), (d_hit), (d_hit),
//     (d_hit), (d_hit), (d_sta), (d_sta), (d_sta), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),//12
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),//15
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_hit), (d_hit), (d_hit), (d_hit), (d_hit),//16
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta),//17
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta),
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta),
//     (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta), (d_sta),//20
// };


#endif // BASIC_STRATEGY_H
