/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


#include "gambler.h"
#include "iostream"



Gambler::Gambler()
{
    bankroll = 0;
}


int Gambler::get_bankroll() const
{
    return bankroll;
}


void Gambler::create_field(int i, const int bet)
{
    Player p(bet);
    for (int j = 0; j < i; ++j) {
        fields.push_back(p);
    }
}

void Gambler::loose(int bet)
{
//     std::cout << "porażka\n";
    bankroll -= bet;
}

void Gambler::win(int bet)
{
//     std::cout << "zwycięstwo\n";
    bankroll += bet;
}

void Gambler::push()
{
//     std::cout << "remis\n";
}

void Gambler::result(const Dealer dealer, int & hands)
{
    for (int j = 0; j < fields.size(); ++j) {
        if (fields[j].get_black_jack() == true && dealer.get_black_jack() == true)
            push();
        else if (fields[j].get_black_jack() == true && dealer.get_black_jack() == false)
            win(fields[j].get_bet()*3/2);
        else if (dealer.get_black_jack() == true) {
            loose(fields[j].get_bet());
//             std::cout << "krupier black jack\n";
        }
        else if (fields[j].get_cards() > 21)
            loose(fields[j].get_bet());
        else if (dealer.get_cards() > 21)
            win(fields[j].get_bet());
        else if (dealer.get_cards() < fields[j].get_cards())
            win(fields[j].get_bet());
        else if (dealer.get_cards() > fields[j].get_cards())
            loose(fields[j].get_bet());
        else
            push();
	hands++;
    }
    
//     std::cout << '\n';

}


void Gambler::reset()
{
    fields.clear();
;
}

void Gambler::one_card(std::vector< Card >& deck, int& counter, int & actual)
{
    for (int j = 0; j<fields.size(); ++j)
        fields[j].add(deck[counter++],actual);
}


void Gambler::print()
{
    for (int j = 0; j < fields.size(); ++j)
        fields[j].print();
}

int Gambler::size()
{
    return fields.size();
}

void Gambler::get_black_jack()
{
    for (int j = 0; j < fields.size(); ++j) {

    }
}

bool Gambler::check_black_jack()
{
    bool check = true;
    for(int j = 0; j < fields.size(); ++j) {
        if (fields[j].get_black_jack() == false)
            check = false;
        break;
    }
    return check;
}

void Gambler::game_gambler(std::vector< Card >& deck, const Dealer dealer, int& counter, int& actual, const int nr_decks)
{
    for (int j = 0; j < fields.size(); ++j) {


        char bufor;
        bool out = false;



        while (fields[j].get_cards() < 21 && out == false) {


            if(fields[j].get_size() == 1) {
                fields[j].add(deck[counter++],actual);
//                 fields[j].print();

            }
            //					gra właściwa
//             std::cout << "twój ruch:\n";
//             std::cin >> bufor;


            /**********************************************
             * 		kalkulator 
	     * 
	     * 			basic strategy
             * **************************************/
//             if(fields[j].can_split()) {
//                 if(fields[j].split_aces()) {
//                     bufor = Basic_strategy::move_split(2, dealer.get_cards());
//                 }
//                 else
//                     bufor = Basic_strategy::move_split(fields[j].get_cards(), dealer.get_cards());
//             }
//             else if (fields[j].ace_soft()) {
//                 bufor = Basic_strategy::move_ace(fields[j].get_cards(), dealer.get_cards());
//             }
//             else
//                 bufor = Basic_strategy::move_normal(fields[j].get_cards(), dealer.get_cards());

/*************************************************************/



            /**********************************************
             * 		kalkulator 
	     * 
	     * 			Hi low
             * **************************************/
            if(fields[j].can_split()) {
                if(fields[j].split_aces()) {
                    bufor = Hi_low_I::move_split(2, dealer.get_cards(),((actual*actual)/nr_decks));
                }
                else
                    bufor = Hi_low_I::move_split(fields[j].get_cards(), dealer.get_cards(),((actual*actual)/nr_decks));
            }
            else if (fields[j].ace_soft()) {
                bufor = Hi_low_I::move_ace(fields[j].get_cards(), dealer.get_cards(),((actual*actual)/nr_decks));
            }
            else
                bufor = Hi_low_I::move_normal(fields[j].get_cards(), dealer.get_cards(),((actual*actual)/nr_decks));

/*************************************************************/


            switch(bufor) {
            case 'f' : {	//hit
                fields[j].add(deck[counter++],actual);
//                 fields[j].print();
                break;
            }
            case 'd': {		//double
                if (fields[j].get_size() == 2) {
//                   std::cout << "double - tylko jedna karta\n";
                    fields[j].double_bet();
                    fields[j].add(deck[counter++],actual);
//                     fields[j].print();
                    out = true;
                }
                else {
//                     std::cout << "double jest możliwy tylko gdy masz dwie karty\n"; //gra właściwa


                    fields[j].add(deck[counter++],actual);		//do kalkulatora
//                     fields[j].print();

                }
                break;
            }
            case 's': {			//stand
//                 std::cout << "bez kart\n";
                out = true;
                break;
            }
            case 'a' : {	//split


                if(fields[j].can_split() == true) {
		  
// 		  std::cout << "split\n";

                    if(fields[j].split_aces()) {
//                         std::cout << "split asów - jeden split, jedna karta, bez black jacka\n";

                        Player p;
                        fields.insert((fields.begin()+j+1), p); 		//rozbicie pól

                        Card c = fields[j].back_card();		//utworzenie nowej karty


                        fields[j+1].add(c,actual);
                        fields[j+1].set_split();

                        fields[j].add(deck[counter++],actual);
                        fields[j].print();
                        if(fields[j].get_cards() == 21)
                            fields[j].only_21();

                        j++;

                        fields[j].add(deck[counter++],actual);
                        fields[j].print();
                        if(fields[j].get_cards() == 21)
                            fields[j].only_21();


                    }
                    else {
                        Player p;
                        fields.insert((fields.begin()+j+1), p); 		//rozbicie pól

                        Card c = fields[j].back_card();		//utworzenie nowej karty


                        fields[j+1].add(c,actual);
                        fields[j+1].set_split();



                    }
                }
                else
//                     std::cout << "nie możesz już splitować kart\n";
                    break;
            }
            case 'g' : {

                break;
            }
            default: {
                std::cout << "zła wartość\n";
                break;
            }
            }
        }
    }
    /********************************************************
    	automat
    *********************************************************/
//         while(fields[j].get_cards() < 17) {
//             fields[j].add(deck[counter++]);
//             fields[j].print();
//         }
//     }
/**********************************************************/
}

bool Gambler::too_many()
{
    bool check = true;
    for (int k = 0; k < fields.size(); ++k) {
        if (fields[k].get_cards() < 22) {
            check = false;
        }
        if(check == false)   break;

    }
    return check;
}

void Gambler::set_bankroll(int i)
{

}

void Gambler::double_card(std::vector<Card> &deck, int &counter, const int i, bool &out, int &actual)
{
    fields[i].add(deck[counter++],actual);
//     fields[i].print();
    out = true;
}
