/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


#include "vector"

#include "player.h"
#include "dealer.h"

#include "basic_strategy.h"
#include "hi_low_i.h"

#ifndef GAMBLER_H
#define GAMBLER_H



class Gambler
{
private:
    int bankroll;
    std::vector<Player> fields;
public:
    Gambler();
    void create_field(int i, const int bet);

    int get_bankroll() const;
    void set_bankroll(int i);



    void loose(int bet);
    void win(int bet);
    void push();

    void loose_no_print(int bet);
    void win_no_print(int bet);
    void push_no_print();

    void reset();
    void one_card_normal(std::vector< Card >& deck, int& counter);
    void one_card_basic(std::vector< Card >& deck, int& counter);
    void one_card_hi_low_I(std::vector<Card> &deck, int &counter, int & actual);


    void print();

    void get_black_jack();
    int size();

    bool check_black_jack();

    void game_gambler_normal(std::vector< Card >& deck, const Dealer dealer, int& counter);
    void game_gambler_basic(std::vector< Card >& deck, const Dealer dealer, int& counter, const int nr_decks);
    void game_gambler_hi_low_I(std::vector< Card >& deck, const Dealer dealer, int& counter, int& actual, const int nr_decks);

    bool too_many();

    void result(const Dealer dealer);
    void result_no_print(const Dealer dealer, int &hands);

    void double_card(std::vector< Card >& deck, int& counter, const int i, bool& out, int& actual);


};

#endif // GAMBLER_H
