/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


#include "game.h"

#include "fstream"
#include "stdlib.h"



void start(std::vector<Card> &deck) {
    int x;
    std::cout << "Podaj liczbę decków:\n";		//do uzupełnienia
    std::cin >> x;
    
    Card::Color c = Card::clubs;
    Card::Value v = Card::A;
//   int licznik = 0;
    for (int h = 0; h < x; ++h)
        for (int i = 1; i < 5; ++i)
            for (int j = 1; j < 14; ++j)
                deck.push_back(Card(c=Card::Color(i),v=Card::Value(j)));
	    

}

void shuffle(std::vector<Card> &deck) {
    std::srand(std::time(0));
    std::random_shuffle(deck.begin(),deck.end());
    
    
    /**********************************
     * plik z kartami
     *********************************/
//     std::string nazwa = "dane";
//     std::ofstream ost(nazwa.c_str());
//     for (int h = 0; h < deck.size(); ++h)
//         ost << deck[h].get_value() << '\n';

}

// void result(Dealer &dealer, Gambler &gambler, Player &player,const int bet) {
// //     if (player.get_black_jack() == true && dealer.get_black_jack() == true)
// //         player.push();
// //     else if (player.get_black_jack() == true && dealer.get_black_jack() == false)
// //         player.win(bet*3/2);
// //     else if (dealer.get_black_jack() == true)
// //         player.loose(bet);
// //     else if (player.get_cards() > 21)
// //         player.loose(bet);
// //     else if (dealer.get_cards() > 21)
// //         player.win(bet);
// //     else if (dealer.get_cards() < player.get_cards())
// //         player.win(bet);
// //     else if (dealer.get_cards() > player.get_cards())
// //         player.loose(bet);
// //     else
// //         player.push();
// //
// //     std::cout << '\n';
//
// }
//
// void double_card(std::vector<Card> &deck, Gambler &gambler, Player &player, int &counter, bool &out) {
//     std::cout << "double - tylko jedna karta\n";
//     player.add(deck[counter++]);
//     out = true;
//
//
// }

void dealer_game(std::vector< Card >& deck, Dealer& dealer, Gambler& gambler, int& counter);

void player_game(std::vector< Card >& deck, Gambler& gambler, int& counter);

// void gambler_game(std::vector< Card >& deck, Gambler& gambler, Player& player, int& counter);

void start_hand(std::vector< Card >& deck, Dealer& dealer, Gambler &gambler, int &counter, const int end) {

      int nr_fields;
      int bet;

    while (counter < end) {

      std::cout << "podaj ilość pól:\n";
      std::cin >>nr_fields;
      
          


      if(nr_fields == 0){
	
	break;
      }
      else{
	
	std::cout << "podaj bet:\n";
	std::cin >> bet;
	
        dealer.reset();
//         player.reset();

        gambler.reset();

        gambler.create_field(nr_fields, bet);


//         player.add(deck[counter++]);
        gambler.one_card(deck,counter);
//         gambler.print();

        dealer.add(deck[counter++]);

//         player.add(deck[counter++]);
        gambler.one_card(deck,counter);

//         gambler.one_card(deck,counter);
        gambler.print();

//         player.print();
        dealer.print();
//         std::cout << '\n';
//         player.check_black_jack();

// 	int rozmiar = gambler.size();
// 	bool sprawdz = true;
// 	for (int j = 0; j < rozmiar; ++j){
// 	  if (gambler
// 	}

        //należy dopracować even money i insurance

        if (gambler.check_black_jack() ==  true) {	//sprawdzenie black jacków graca i odpowiednie zachowanie krupiera
            if (dealer.get_cards()==1 || dealer.get_cards()==10) {
//                 return;
//             }
//             else {
                dealer.add(deck[counter++]);

            }


        }
        else {
            gambler.game_gambler(deck, counter);	//w przeciwnym wypadku standardowa gra
            dealer_game(deck, dealer, gambler, counter);

        }

        gambler.result(dealer);
      }

//         if (player.get_black_jack() == true) {	//obsługa black jacka gracza
//             std::cout << "gracz black jack\n";
//
//             if (dealer.get_cards()==1 || dealer.get_cards()==10) {
// //                 return;
// //             }
// //             else {
//                 dealer.add(deck[counter++]);
//
//             }
//         }
//
//         else {
//             player_game(deck, gambler, player, counter);
//             dealer_game(deck, dealer, gambler, player, counter);
//         }
//
//         result(dealer, gambler, player, bet);
    }
}

// void player_game(std::vector< Card >& deck, Gambler& gambler, int& counter) {
//     char bufor;
//     bool out = false;
//
//
//
//     while (player.get_cards() < 22 && out == false) {
//
//         std::cout << "twój ruch:\n";
//         std::cin >> bufor;
//
//
//         switch(bufor) {
//         case 'f' : {
//             player.add(deck[counter++]);
//             player.print();
//             break;
//         }
//         case 'd': {
//             double_card(deck,gambler, player,counter,out);
//             player.print();
//             break;
//         }
//         case 's': {
//             std::cout << "bez kart\n";
//             out = true;
//             //split
//             break;
//         }
//         case 'a' : {
//             //split
//             break;
//         }
//         default: {
//             std::cout << "zła wartość\n";
//             break;
//         }
//         }
//
// //         player.add(deck[counter++]);
// //         player.print();
//
//     }
//
// //    std::cout << "karta gracza:
// //     player.print();
//
// }

void dealer_game(std::vector< Card >& deck, Dealer& dealer, Gambler& gambler, int& counter) {
    if (gambler.too_many() == true)
        return;
    else
        while (dealer.get_cards() < 17) {
            dealer.add(deck[counter++]);

            dealer.print();
        }
//     dealer.print();
}

// void gambler_game(std::vector< Card >& deck, Gambler& gambler, Player& player, int& counter)
// {
//
// }



void game(std::vector< Card >& deck, Dealer& dealer, Gambler& gambler)
{

    int counter = 0; //licznik dla kart

    int all_games;
    int nr_game = 0;

    start(deck);

    int end = deck.size()*2/3;

    std::cout << "podaj liczbę gier:\n";		//do uzupełnienia
    std::cin >> all_games;

    while (nr_game ++ < all_games) {
        shuffle(deck);
        counter = 0;
        start_hand(deck,dealer,gambler,counter,end);
    }

    std::cout << "ilość kart: " << counter << "\n";
    std::cout << "wynik gracza: " <<  gambler.get_bankroll() << '\n';

}

