/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


#include "game.h"



void start(std::vector<Card> &deck) {
    int x = 6;
    std::cout << "Podaj liczbę decków:\n";		//do uzupełnienia
    Card::Color c = Card::clubs;
    Card::Value v = Card::A;
//   int licznik = 0;
    for (int h = 0; h < x; ++h)
        for (int i = 1; i < 5; ++i)
            for (int j = 1; j < 14; ++j)
                deck.push_back(Card(c=Card::Color(i),v=Card::Value(j)));
}

void shuffle(std::vector<Card> &deck) {
    std::srand(std::time(0));
    std::random_shuffle(deck.begin(),deck.end());

}

void result(Dealer &dealer, Player &player,const int bet) {
    if (player.get_black_jack() == true && dealer.get_black_jack() == true)
        player.push();
    else if (player.get_black_jack() == true && dealer.get_black_jack() == false)
        player.win(bet*3/2);
    else if (dealer.get_black_jack() == true)
        player.loose(bet);
    else if (player.get_cards() > 21)
        player.loose(bet);
    else if (dealer.get() > 21)
        player.win(bet);
    else if (dealer.get() < player.get_cards())
        player.win(bet);
    else if (dealer.get() > player.get_cards())
        player.loose(bet);
    else
        player.push();

    std::cout << '\n';

}

void dealer_game(std::vector< Card >& deck, Dealer& dealer, const Player player, int& counter);

void player_game(std::vector<Card> &deck, Player &player, int &counter);

void start_hand(std::vector< Card >& deck, Dealer& dealer, Player &player, int &counter, const int end) {
    int bet = 10;

    while (counter < end) {
        dealer.reset();
        player.reset();

        player.add(deck[counter++]);
        dealer.add(deck[counter++]);
        player.add(deck[counter++]);


        player.print();
        dealer.print();
//         std::cout << '\n';
        player.check_black_jack();

        if (player.get_black_jack() == true) {
            std::cout << "gracz black jack\n";

            if (dealer.get()>1 && dealer.get()<10) {
                return;
            }
            else {
                dealer.add(deck[counter++]);

            }
        }

        else {
            player_game(deck, player, counter);
            dealer_game(deck, dealer, player, counter);
        }

        result(dealer, player, bet);
    }
}

void player_game(std::vector<Card> &deck, Player &player, int &counter) {
    char bufor;
//     std::cout << "twój ruch:\n";
//         std::cin >> bufor;
    while (player.get_cards() < 17) {


        player.add(deck[counter++]);
        player.print();

    }

//    std::cout << "karta gracza:
//     player.print();

}

void dealer_game(std::vector<Card> &deck, Dealer &dealer, const Player player,  int &counter) {
    if (player.get_cards() > 21)
        return;
    else
        while (dealer.get() < 17) {
            dealer.add(deck[counter++]);

            dealer.print();
        }
//     dealer.print();
}



void game(std::vector< Card >& deck, Dealer& dealer, Player &player)
{

    int counter = 0; //licznik dla kart

    int all_games = 1;
    int nr_game = 0;

    start(deck);

    int end = deck.size()*2/3;

    std::cout << "podaj liczbę gier:\n";		//do uzupełnienia


    while (nr_game ++ < all_games) {
        shuffle(deck);
        counter = 0;
        start_hand(deck,dealer,player,counter,end);
    }
    std::cout << "wynik gracza: " <<  player.get_bankroll() << '\n';

}

