/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


#include "game.h"

#include "fstream"
#include "stdlib.h"



void start(std::vector<Card> &deck) {
    int x = 6;
    std::cout << "Podaj liczbę decków:\n";		//gra właściwa;
//     std::cin >> x;

    Card::Color c = Card::clubs;
    Card::Value v = Card::A;
    for (int h = 0; h < x; ++h)
        for (int i = 1; i < 5; ++i)
            for (int j = 1; j < 14; ++j)
                deck.push_back(Card(c=Card::Color(i),v=Card::Value(j)));


}

void shuffle(std::vector<Card> &deck) {
    std::srand(std::time(0));
    std::random_shuffle(deck.begin(),deck.end());


    /**********************************
     * plik z kartami
     *********************************/
//     std::string nazwa = "dane";
//     std::ofstream ost(nazwa.c_str());
//     for (int h = 0; h < deck.size(); ++h)
//         ost << deck[h].get_value() << '\n';
/*********************************************/

}


void dealer_game(std::vector< Card >& deck, Dealer& dealer, Gambler& gambler, int& counter);

void player_game(std::vector< Card >& deck, Gambler& gambler, int& counter);

void start_hand(std::vector< Card >& deck, Dealer& dealer, Gambler &gambler, int &counter, const int end) {

    int nr_fields = 1; //kalkulator
    int bet = 10;

    while (counter < end) {
//						gra właściwa
//       std::cout << "podaj ilość pól:\n";
//       std::cin >>nr_fields;




        if(nr_fields == 0) {

            break;
        }
        else {
            //			gra właściwa
// 	std::cout << "podaj bet:\n";
// 	std::cin >> bet;
//
            dealer.reset();

            gambler.reset();

            gambler.create_field(nr_fields, bet);


            gambler.one_card(deck,counter);

            dealer.add(deck[counter++]);

            gambler.one_card(deck,counter);

            gambler.print();

            dealer.print();


            //należy dopracować even money i insurance

            if (gambler.check_black_jack() ==  true) {	//sprawdzenie black jacków graca i odpowiednie zachowanie krupiera
                if (dealer.get_cards()==1 || dealer.get_cards()==10) {

                    dealer.add(deck[counter++]);

                }


            }
            else {
                gambler.game_gambler(deck, dealer, counter);	//w przeciwnym wypadku standardowa gra
                dealer_game(deck, dealer, gambler, counter);

            }

            gambler.result(dealer);
        }

    }
}



void dealer_game(std::vector< Card >& deck, Dealer& dealer, Gambler& gambler, int& counter) {
    if (gambler.too_many() == true)
        return;
    else
        while (dealer.get_cards() < 17) {
            dealer.add(deck[counter++]);

            dealer.print();
        }
    dealer.print();
}




void game(std::vector< Card >& deck, Dealer& dealer, Gambler& gambler)
{

    int counter = 0; //licznik dla kart

    int all_games = 100;
    int nr_game = 0;

    start(deck);

    int end = deck.size()*2/3;

    std::cout << "podaj liczbę gier:\n";		//gra właściwa

    while (nr_game ++ < all_games) {
        shuffle(deck);
        counter = 0;
        start_hand(deck,dealer,gambler,counter,end);
    }

    std::cout << "wynik gracza: " <<  gambler.get_bankroll() << '\n';

}

