/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/


#include "player.h"
#include "iostream"

Player::Player()
{
    cards = 0;
    bankroll = 0;

    black_jack = false;
    soft_ace = false;
}

Player::~Player()
{

}

void Player::add(const Card card)
{
    card.print();
    if (card.get_value() == 1) option::soft_ace(soft_ace,cards); 		//test
    cards += card.get_value();
    option::use_ace(soft_ace,cards);
}

void Player::print()
{
    std::cout << "\t\t\tgracz: ";
    if (cards < 22)
        std::cout << cards << '\n';
    else
        std::cout << "za dużo\n";

}

void Player::reset()
{
    cards = 0;
    soft_ace = false;
    black_jack = false;
}

int Player::get_bankroll() const
{
    return bankroll;
}

int Player::get_cards() const
{
    return cards;
}

void Player::loose(const int bet)
{
    std::cout << "porażka\n";
    bankroll -= bet;
}

void Player::win(const int bet)
{
    std::cout << "zwycięstwo\n";
    bankroll += bet;
}

void Player::push()
{
    std::cout << "remis\n";
}

void Player::check_black_jack()
{
    if (cards == 21) black_jack = true;
}

bool Player::get_black_jack() const
{
    return black_jack;
}

